=== MFW3D/MFW3DNet/bin/Release/Config/Moon/LayerSet.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by Patrick Hogan (private) -->
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by Patrick Hogan (private) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="LayerSet" type="Type_LayerSet"/>
	<xs:complexType name="Type_Vector3">
		<xs:sequence>
			<xs:element name="x" type="xs:double"/>
			<xs:element name="y" type="xs:double"/>
			<xs:element name="z" type="xs:double"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Type_Orientation">
		<xs:annotation>
			<xs:documentation>Units are in degrees</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="RotationX" type="xs:float"/>
			<xs:element name="RotationY" type="xs:float"/>
			<xs:element name="RotationZ" type="xs:float"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Type_WMSAccessor">
		<xs:sequence>
			<xs:element name="Username" type="xs:string" minOccurs="0"/>
			<xs:element name="Password" type="xs:string" minOccurs="0"/>
			<xs:element name="ServerGetMapUrl" type="xs:string"/>
			<xs:element name="Version" type="xs:string"/>
			<xs:element name="ImageFormat" type="xs:string"/>
			<xs:element name="WMSLayerName" type="xs:string"/>
			<xs:element name="WMSLayerStyle" type="xs:string" minOccurs="0"/>
			<xs:element name="UseTransparency" type="xs:boolean"/>
			<xs:element name="CacheExpirationTime" type="Type_SimpleTimeSpan" minOccurs="0"/>
			<xs:element name="BoundingBoxOverlap" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:double">
						<xs:minInclusive value="0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ServerLogoFilePath" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Type_LatLonBoundingBox">
		<xs:sequence>
			<xs:element name="North" type="Type_LatitudeCoordinate"/>
			<xs:element name="South" type="Type_LatitudeCoordinate"/>
			<xs:element name="West" type="Type_LongitudeCoordinate"/>
			<xs:element name="East" type="Type_LongitudeCoordinate"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Type_LatitudeCoordinate">
		<xs:sequence>
			<xs:element name="Value">
				<xs:simpleType>
					<xs:restriction base="xs:double">
						<xs:minInclusive value="-90"/>
						<xs:maxInclusive value="90"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Type_LongitudeCoordinate">
		<xs:sequence>
			<xs:element name="Value">
				<xs:simpleType>
					<xs:restriction base="xs:double">
						<xs:minInclusive value="-180"/>
						<xs:maxInclusive value="180"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Type_RGBColor">
		<xs:sequence>
			<xs:element name="Red">
				<xs:simpleType>
					<xs:restriction base="xs:unsignedByte">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Green">
				<xs:simpleType>
					<xs:restriction base="xs:unsignedByte">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Blue">
				<xs:simpleType>
					<xs:restriction base="xs:unsignedByte">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Type_DisplayFont">
		<xs:sequence>
			<xs:element name="Family" type="xs:string"/>
			<xs:element name="Size" type="xs:float"/>
			<xs:element name="Style" minOccurs="0">
				<xs:complexType>
					<xs:sequence minOccurs="0">
						<xs:element name="IsBold" type="xs:boolean" minOccurs="0"/>
						<xs:element name="IsItalic" type="xs:boolean" minOccurs="0"/>
						<xs:element name="IsUnderlined" type="xs:boolean" minOccurs="0"/>
						<xs:element name="IsStrikeout" type="xs:boolean" minOccurs="0"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Type_LayerSet">
		<xs:sequence>
			<xs:group ref="Layers"/>
			<xs:element name="ChildLayerSet" type="Type_LayerSet" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="ExtendedInformation" type="Type_ExtendedInformation" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="Name" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="ShowOnlyOneLayer" type="xs:boolean" use="required"/>
		<xs:attribute name="ShowAtStartup" type="xs:boolean" use="required"/>
	</xs:complexType>
	<xs:complexType name="Type_PathList">
		<xs:sequence>
			<xs:element name="Name" type="xs:string"/>
			<xs:element name="DistanceAboveSurface" type="xs:float"/>
			<xs:element name="MinDisplayAltitude">
				<xs:simpleType>
					<xs:restriction base="xs:double">
						<xs:minInclusive value="0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="MaxDisplayAltitude">
				<xs:simpleType>
					<xs:restriction base="xs:double">
						<xs:minInclusive value="0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="PathsDirectory" type="xs:string"/>
			<xs:element name="RGBColor" type="Type_RGBColor" minOccurs="0"/>
			<xs:element name="WinColorName" type="xs:string" minOccurs="0"/>
			<xs:element name="ExtendedInformation" type="Type_ExtendedInformation" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="ShowAtStartup" type="xs:boolean" use="required"/>
	</xs:complexType>
	<xs:complexType name="Type_ImageLayer">
		<xs:sequence>
			<xs:element name="Name">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="DistanceAboveSurface" type="xs:double"/>
			<xs:element name="BoundingBox" type="Type_LatLonBoundingBox"/>
			<xs:element name="TexturePath" type="xs:string"/>
			<xs:element name="Opacity">
				<xs:simpleType>
					<xs:restriction base="xs:unsignedByte">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="TerrainMapped" type="xs:boolean"/>
			<xs:element name="TransparencyColor" type="Type_RGBColor" minOccurs="0"/>
			<xs:element name="LegendImagePath" type="xs:string" minOccurs="0"/>
			<xs:element name="ExtendedInformation" type="Type_ExtendedInformation" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="ShowAtStartup" type="xs:boolean" use="required"/>
	</xs:complexType>
	<xs:complexType name="Type_QuadTileSet">
		<xs:sequence>
			<xs:element name="Name" type="xs:string"/>
			<xs:element name="DistanceAboveSurface" type="xs:double"/>
			<xs:element name="BoundingBox" type="Type_LatLonBoundingBox"/>
			<xs:element name="TerrainMapped" type="xs:boolean"/>
			<xs:element name="ImageAccessor" type="Type_ImageAccessor"/>
			<xs:element name="TileDrawDistanceFactor" type="xs:float" minOccurs="0"/>
			<xs:element name="TileSpreadFactor" type="xs:float" minOccurs="0"/>
			<xs:element name="ExtendedInformation" type="Type_ExtendedInformation" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="ShowAtStartup" type="xs:boolean" use="required"/>
	</xs:complexType>
	<xs:complexType name="Type_Icon">
		<xs:sequence>
			<xs:element name="Name" type="xs:string"/>
			<xs:element name="Latitude" type="Type_LatitudeCoordinate"/>
			<xs:element name="Longitude" type="Type_LongitudeCoordinate"/>
			<xs:element name="DistanceAboveSurface" type="xs:double"/>
			<xs:element name="MinimumDisplayAltitude" type="xs:decimal" minOccurs="0"/>
			<xs:element name="MaximumDisplayAltitude" type="xs:double" minOccurs="0"/>
			<xs:element name="TextureFilePath" type="xs:string"/>
			<xs:element name="TextureWidthPixels" type="xs:unsignedInt"/>
			<xs:element name="TextureHeightPixels" type="xs:unsignedInt"/>
			<xs:element name="IconWidthPixels" type="xs:unsignedInt"/>
			<xs:element name="IconHeightPixels" type="xs:unsignedInt"/>
			<xs:element name="Caption" type="Type_Caption" minOccurs="0"/>
			<xs:element name="ClickableUrl" type="xs:string" minOccurs="0"/>
			<xs:element name="MouseoverTextColor" type="Type_RGBColor" minOccurs="0"/>
			<xs:element name="ExtendedInformation" type="Type_ExtendedInformation" minOccurs="0"/>
			<xs:element name="Description" type="xs:string" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="ShowAtStartup" type="xs:boolean" use="required"/>
	</xs:complexType>
	<xs:complexType name="Type_TiledPlacenameSet">
		<xs:sequence>
			<xs:element name="Name" type="xs:string"/>
			<xs:element name="DistanceAboveSurface" type="xs:double"/>
			<xs:element name="MinimumDisplayAltitude">
				<xs:simpleType>
					<xs:restriction base="xs:double">
						<xs:minInclusive value="0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="MaximumDisplayAltitude">
				<xs:simpleType>
					<xs:restriction base="xs:double">
						<xs:minInclusive value="0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="PlacenameListFilePath" type="xs:string"/>
			<xs:element name="DisplayFont" type="Type_DisplayFont" minOccurs="0"/>
			<xs:element name="RGBColor" type="Type_RGBColor" minOccurs="0"/>
			<xs:element name="WinColorName" type="xs:string" minOccurs="0"/>
			<xs:element name="IconFilePath" type="xs:string" minOccurs="0"/>
			<xs:element name="ExtendedInformation" type="Type_ExtendedInformation" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="ShowAtStartup" type="xs:boolean" use="required"/>
	</xs:complexType>
	<xs:complexType name="Type_MeshLayer">
		<xs:sequence>
			<xs:element name="Name" type="xs:string"/>
			<xs:element name="DistanceAboveSurface">
				<xs:simpleType>
					<xs:restriction base="xs:float">
						<xs:minInclusive value="0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Latitude" type="Type_LatitudeCoordinate"/>
			<xs:element name="Longitude" type="Type_LongitudeCoordinate"/>
			<xs:element name="Orientation" type="Type_Orientation"/>
			<xs:element name="ScaleFactor">
				<xs:simpleType>
					<xs:restriction base="xs:float">
						<xs:minInclusive value="0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="MinViewRange">
				<xs:simpleType>
					<xs:restriction base="xs:float">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="180"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="MaxViewRange">
				<xs:simpleType>
					<xs:restriction base="xs:float">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="180"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="MeshFilePath">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ExtendedInformation" type="Type_ExtendedInformation" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="ShowAtStartup" type="xs:boolean" use="required"/>
	</xs:complexType>
	<xs:group name="Layers">
		<xs:sequence>
			<xs:element name="ImageLayer" type="Type_ImageLayer" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="QuadTileSet" type="Type_QuadTileSet" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="ShapeFileLayer" type="Type_ShapeFileLayer" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="MeshLayer" type="Type_MeshLayer" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="PathList" type="Type_PathList" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Icon" type="Type_Icon" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="TiledPlacenameSet" type="Type_TiledPlacenameSet" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:group>
	<xs:complexType name="Type_ExtendedInformation">
		<xs:sequence>
			<xs:element name="Abstract" type="xs:string" minOccurs="0"/>
			<xs:element name="ToolBarImage" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Type_ShapeFileLayer">
		<xs:sequence>
			<xs:element name="Name" type="xs:string"/>
			<xs:element name="DistanceAboveSurface" type="xs:double"/>
			<xs:element name="MasterFilePath" type="xs:string"/>
			<xs:element name="MinimumViewAltitude" type="xs:double"/>
			<xs:element name="MaximumViewAltitude" type="xs:double"/>
			<xs:element name="ShowPoints" type="xs:boolean" minOccurs="0"/>
			<xs:element name="ShowBoundaries" type="xs:boolean" minOccurs="0"/>
			<xs:element name="ShowFilledRegions" type="xs:boolean" minOccurs="0"/>
			<xs:element name="ScalarKey" type="xs:string" minOccurs="0"/>
			<xs:element name="ShowScalarValues" type="xs:boolean" minOccurs="0"/>
			<xs:element name="DisplayFont" type="Type_DisplayFont" minOccurs="0"/>
			<xs:element name="RGBColor" type="Type_RGBColor" minOccurs="0"/>
			<xs:element name="WinColorName" type="xs:string" minOccurs="0"/>
			<xs:element name="ExtendedInformation" type="Type_ExtendedInformation" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="ShowAtStartup" type="xs:boolean" use="required"/>
	</xs:complexType>
	<xs:complexType name="Type_ImageAccessor">
		<xs:sequence>
			<xs:element name="LevelZeroTileSizeDegrees">
				<xs:simpleType>
					<xs:restriction base="xs:double">
						<xs:minExclusive value="0"/>
						<xs:maxInclusive value="180"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="NumberLevels" type="xs:unsignedInt"/>
			<xs:element name="TextureSizePixels" type="xs:unsignedInt"/>
			<xs:element name="ImageFileExtension" type="xs:string"/>
			<xs:element name="PermanantDirectory" type="xs:string" minOccurs="0"/>
			<xs:choice minOccurs="0">
				<xs:element name="DuplicateTilePath" type="xs:string"/>
				<xs:element name="WMSAccessor" type="Type_WMSAccessor"/>
				<xs:element name="ImageTileService" type="Type_ImageTileService"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Type_ImageTileService">
		<xs:sequence>
			<xs:element name="ServerUrl" type="xs:string"/>
			<xs:element name="DataSetName" type="xs:string"/>
			<xs:element name="CacheExpirationTime" type="Type_SimpleTimeSpan" minOccurs="0"/>
			<xs:element name="ServerLogoFilePath" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Type_SimpleTimeSpan">
		<xs:sequence>
			<xs:element name="Days" type="xs:unsignedInt"/>
			<xs:element name="Hours" type="xs:integer"/>
			<xs:element name="Mins" type="xs:unsignedInt"/>
			<xs:element name="Seconds" type="xs:unsignedInt"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Type_Caption">
		<xs:sequence>
			<xs:element name="CaptionText" type="xs:string"/>
			<xs:element name="DisplayFont" type="Type_DisplayFont" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== MFW3D/MFW3DNet/bin/Debug/Config/Mars/OnMars.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
OnMars.xml
JPL WMS Planeraty Server Configuration
 -->
<LayerSet Name="OnMars WMS" ShowOnlyOneLayer="false" ShowAtStartup="false" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="LayerSet.xsd">
	<QuadTileSet ShowAtStartup="true">
		<Name>MOC Narrow Angle</Name>
		<DistanceAboveSurface>0</DistanceAboveSurface>
		<BoundingBox>
			<North>
				<Value>76</Value>
			</North>
			<South>
				<Value>-76</Value>
			</South>
			<West>
				<Value>-180</Value>
			</West>
			<East>
				<Value>180</Value>
			</East>
		</BoundingBox>
		<TerrainMapped>true</TerrainMapped>
		<ImageAccessor>
			<LevelZeroTileSizeDegrees>4.0</LevelZeroTileSizeDegrees>
			<NumberLevels>7</NumberLevels>
			<TextureSizePixels>512</TextureSizePixels>
			<ImageFileExtension>jpg</ImageFileExtension>
			<WMSAccessor>
				<ServerGetMapUrl>http://OnMars.jpl.nasa.gov/wms.cgi</ServerGetMapUrl>
				<ServiceName>OGC:WMS</ServiceName>
				<Version>1.1.1</Version>
				<ImageFormat>image/jpeg</ImageFormat>
				<WMSLayerName>moc_na</WMSLayerName>
				<UseTransparency>true</UseTransparency>
				<ServerLogoFilePath>Data\Icons\Interface\earth-western.png</ServerLogoFilePath>
			</WMSAccessor>
		</ImageAccessor>
		<TransparentMinValue>0</TransparentMinValue>
		<TransparentMaxValue>5</TransparentMaxValue>
	</QuadTileSet>
	<ExtendedInformation>
		<ToolBarImage>Data\Icons\Interface\earth-western.png</ToolBarImage>
	</ExtendedInformation>
</LayerSet>

=== MFW3D/MFW3DNet/bin/Release/Plugins/Dstile/skeleton.xml
<?xml version="1.0" encoding="utf-8"?>
<LayerSet Name="Dstile Ingested Images" ShowOnlyOneLayer="true" ShowAtStartup="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="LayerSet.xsd">
  <QuadTileSet ShowAtStartup="true">
    <Name>Layername</Name>
    <DistanceAboveSurface>0</DistanceAboveSurface>
    <BoundingBox>
      <North>
        <Value>90.0</Value>
      </North>
      <South>
        <Value>-90.0</Value>
      </South>
      <West>
        <Value>-180.0</Value>
      </West>
      <East>
        <Value>180.0</Value>
      </East>
    </BoundingBox>
    <TerrainMapped>true</TerrainMapped>
    <RenderStruts>false</RenderStruts>
    <ImageAccessor>
      <LevelZeroTileSizeDegrees>1.0</LevelZeroTileSizeDegrees>
      <NumberLevels>4</NumberLevels>
      <TextureSizePixels>512</TextureSizePixels>
      <ImageFileExtension>jpg</ImageFileExtension>
      <PermanentDirectory>Data\Earth\Layername</PermanentDirectory>
    </ImageAccessor>
    <TransparentMinValue>0</TransparentMinValue>
    <TransparentMaxValue>20</TransparentMaxValue>
  </QuadTileSet>
</LayerSet>

=== MFW3D/MFW3DNet/bin/Release/Config/Venus/@Images.xml
<?xml version="1.0" encoding="UTF-8"?>

<LayerSet Name="Images" ShowOnlyOneLayer="true" ShowAtStartup="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="LayerSet.xsd">

<ChildLayerSet Name="Magellan Imaging Radar (Color)" ShowOnlyOneLayer="false" ShowAtStartup="true">
	<ImageLayer ShowAtStartup="true">
		<Name>Color Base</Name>
		<DistanceAboveSurface>0</DistanceAboveSurface>
		<BoundingBox>
			<North>
				<Value>90.0</Value>
			</North>
			<South>
				<Value>-90.0</Value>
			</South>
			<West>
				<Value>-180.0</Value>
			</West>
			<East>
				<Value>180.0</Value>
			</East>
		</BoundingBox>
		<TexturePath>http://worldwind25.arc.nasa.gov/VenusBase/venus_magellan_fmap_color.jpg</TexturePath>
		<Opacity>255</Opacity>
		<TerrainMapped>false</TerrainMapped>
	</ImageLayer>
	<QuadTileSet ShowAtStartup="true">
		<Name>Color Tiled</Name>
		<DistanceAboveSurface>0</DistanceAboveSurface>
		<BoundingBox>
			<North>
				<Value>90.0</Value>
			</North>
			<South>
				<Value>-90.0</Value>
			</South>
			<West>
				<Value>-180.0</Value>
			</West>
			<East>
				<Value>180.0</Value>
			</East>
		</BoundingBox>
		<TerrainMapped>false</TerrainMapped>
		<ImageAccessor>
			<LevelZeroTileSizeDegrees>45.0</LevelZeroTileSizeDegrees>
			<NumberLevels>4</NumberLevels>
			<TextureSizePixels>512</TextureSizePixels>
			<ImageFileExtension>jpg</ImageFileExtension>
			<ImageTileService>
				<ServerUrl>http://worldwind25.arc.nasa.gov/venus/venus.aspx</ServerUrl>
				<DataSetName>fmap-color</DataSetName>
				<ServerLogoFilePath>Data\Icons\Interface\meatball.png</ServerLogoFilePath>
			</ImageTileService>
		</ImageAccessor>
	</QuadTileSet>
	<ExtendedInformation>
		<ToolBarImage>Add-ons\Venus\magellan-color.png</ToolBarImage>
	</ExtendedInformation>
</ChildLayerSet>

<ChildLayerSet Name="Magellan Imaging Radar (Grey)" ShowOnlyOneLayer="false" ShowAtStartup="false">
	<ImageLayer ShowAtStartup="true">
		<Name>Grey Base</Name>
		<DistanceAboveSurface>0</DistanceAboveSurface>
		<BoundingBox>
			<North>
				<Value>90.0</Value>
			</North>
			<South>
				<Value>-90.0</Value>
			</South>
			<West>
				<Value>-180.0</Value>
			</West>
			<East>
				<Value>180.0</Value>
			</East>
		</BoundingBox>
		<TexturePath>http://worldwind25.arc.nasa.gov/VenusBase/venus_magellan_fmap_grey.jpg</TexturePath>
		<Opacity>255</Opacity>
		<TerrainMapped>false</TerrainMapped>
	</ImageLayer>
	<QuadTileSet ShowAtStartup="true">
		<Name>Grey Tiled</Name>
		<DistanceAboveSurface>0</DistanceAboveSurface>
		<BoundingBox>
			<North>
				<Value>90.0</Value>
			</North>
			<South>
				<Value>-90.0</Value>
			</South>
			<West>
				<Value>-180.0</Value>
			</West>
			<East>
				<Value>180.0</Value>
			</East>
		</BoundingBox>
		<TerrainMapped>false</TerrainMapped>
		<ImageAccessor>
			<LevelZeroTileSizeDegrees>45.0</LevelZeroTileSizeDegrees>
			<NumberLevels>4</NumberLevels>
			<TextureSizePixels>512</TextureSizePixels>
			<ImageFileExtension>jpg</ImageFileExtension>
			<ImageTileService>
				<ServerUrl>http://worldwind25.arc.nasa.gov/venus/venus.aspx</ServerUrl>
				<DataSetName>fmap-grey</DataSetName>
				<ServerLogoFilePath>Data\Icons\Interface\meatball.png</ServerLogoFilePath>
			</ImageTileService>
		</ImageAccessor>
	</QuadTileSet>
	<ExtendedInformation>
		<ToolBarImage>Add-ons\Venus\magellan-gray.png</ToolBarImage>
	</ExtendedInformation>
</ChildLayerSet>

<ChildLayerSet Name="Shaded Relief" ShowOnlyOneLayer="false" ShowAtStartup="false">
	<ImageLayer ShowAtStartup="true">
		<Name>Shaded Relief</Name>
		<DistanceAboveSurface>0</DistanceAboveSurface>
		<BoundingBox>
			<North>
				<Value>90.0</Value>
			</North>
			<South>
				<Value>-90.0</Value>
			</South>
			<West>
				<Value>-180.0</Value>
			</West>
			<East>
				<Value>180.0</Value>
			</East>
		</BoundingBox>
		<TexturePath>http://worldwind25.arc.nasa.gov/VenusBase/w001001_2048x1024.jpg</TexturePath>
		<Opacity>255</Opacity>
		<TerrainMapped>false</TerrainMapped>
	</ImageLayer>
	<QuadTileSet ShowAtStartup="true">
		<Name>Shaded Relief Tiled</Name>
		<DistanceAboveSurface>0</DistanceAboveSurface>
		<BoundingBox>
			<North>
				<Value>90.0</Value>
			</North>
			<South>
				<Value>-90.0</Value>
			</South>
			<West>
				<Value>-180.0</Value>
			</West>
			<East>
				<Value>180.0</Value>
			</East>
		</BoundingBox>
		<TerrainMapped>false</TerrainMapped>
		<ImageAccessor>
			<LevelZeroTileSizeDegrees>45.0</LevelZeroTileSizeDegrees>
			<NumberLevels>2</NumberLevels>
			<TextureSizePixels>512</TextureSizePixels>
			<ImageFileExtension>jpg</ImageFileExtension>
			<ImageTileService>
				<ServerUrl>http://worldwind25.arc.nasa.gov/venus/venus.aspx</ServerUrl>
				<DataSetName>Topo</DataSetName>
				<ServerLogoFilePath>Data\Icons\Interface\meatball.png</ServerLogoFilePath>
			</ImageTileService>
		</ImageAccessor>
	</QuadTileSet>
	<ExtendedInformation>
		<ToolBarImage>Add-ons\Venus\magellan-shaded.png</ToolBarImage>
	</ExtendedInformation>
</ChildLayerSet>

</LayerSet>

=== MFW3D/MFW3DNet/bin/Debug/Config/SDSS/@Images.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by Patrick Hogan (private) -->
<LayerSet Name="Sky" ShowOnlyOneLayer="false" ShowAtStartup="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="LayerSet.xsd">

	<ChildLayerSet Name="Survey Imagery" ShowOnlyOneLayer="false" ShowAtStartup="true">
		<QuadTileSet ShowAtStartup="true">
			<Name> Sloan Digital Sky Server</Name>
			<DistanceAboveSurface>0</DistanceAboveSurface>
			<BoundingBox>
				<North>
					<Value>90.</Value>
				</North>
				<South>
					<Value>-90.</Value>
				</South>
				<West>
					<Value>-180.</Value>
				</West>
				<East>
					<Value>180.</Value>
				</East>
			</BoundingBox>
			<TerrainMapped>false</TerrainMapped>
			<ImageAccessor>
				<LevelZeroTileSizeDegrees>36.</LevelZeroTileSizeDegrees>
				<NumberLevels>21</NumberLevels>
				<TextureSizePixels>512</TextureSizePixels>
				<ImageFileExtension>jpeg</ImageFileExtension>
		 	<WMSAccessor>
		 	  <ServerGetMapUrl>http://nvogre.phyast.pitt.edu/cgi-bin/nvomapserv</ServerGetMapUrl>
		 	  <ServiceName>WMS</ServiceName>
		 	  <Version>1.1.1</Version>
		 	  <ImageFormat>image/jpeg</ImageFormat>
	 		  <WMSLayerName>sdssimgl0,sdssimgl1,sdssimgl2,sdssimgl3</WMSLayerName>
	 		  <UseTransparency>true</UseTransparency>
			  <Opacity>250</Opacity>
	 		  <ServerLogoFilePath>add-ons\sdss\sdss\sdss.png</ServerLogoFilePath>
		 	 </WMSAccessor>
			</ImageAccessor>
			<ExtendedInformation>
				<ToolBarImage>add-ons\sdss\sdss\sdss.png</ToolBarImage>
			</ExtendedInformation>
		</QuadTileSet>


		<QuadTileSet ShowAtStartup="false">
			<Name> WMAP Image Server</Name>
			<DistanceAboveSurface>0</DistanceAboveSurface>
			<BoundingBox>
				<North>
					<Value>90.</Value>
				</North>
				<South>
					<Value>-90.</Value>
				</South>
				<West>
					<Value>-180.</Value>
				</West>
				<East>
					<Value>180.</Value>
				</East>
			</BoundingBox>
			<TerrainMapped>false</TerrainMapped>
			<ImageAccessor>
				<LevelZeroTileSizeDegrees>36.</LevelZeroTileSizeDegrees>
				<NumberLevels>21</NumberLevels>
				<TextureSizePixels>512</TextureSizePixels>
				<ImageFileExtension>jpeg</ImageFileExtension>
		 	<WMSAccessor>
		 	  <ServerGetMapUrl>http://nvogre.phyast.pitt.edu/cgi-bin/nvomapserv</ServerGetMapUrl>
		 	  <ServiceName>WMS</ServiceName>
		 	  <Version>1.1.1</Version>
		 	  <ImageFormat>image/jpeg</ImageFormat>
	 		  <WMSLayerName>wmap0</WMSLayerName>
	 		  <UseTransparency>true</UseTransparency>
			  <Opacity>100</Opacity>
	 		  <ServerLogoFilePath>add-ons\sdss\sdss\blob.png</ServerLogoFilePath>
		 	 </WMSAccessor>
			</ImageAccessor>
			<ExtendedInformation>
				<ToolBarImage>add-ons\sdss\sdss\blob.png</ToolBarImage>
			</ExtendedInformation>
		</QuadTileSet>

	</ChildLayerSet>
	<ChildLayerSet Name="Footprint Imagery" ShowOnlyOneLayer="false" ShowAtStartup="true">
		<QuadTileSet ShowAtStartup="false">
			<Name>SDSS Footprint</Name>
			<DistanceAboveSurface>0</DistanceAboveSurface>
			<BoundingBox>
				<North>
					<Value>90.</Value>
				</North>
				<South>
					<Value>-90.</Value>
				</South>
				<West>
					<Value>-180.</Value>
				</West>
				<East>
					<Value>180.</Value>
				</East>
			</BoundingBox>
      <Opacity>160</Opacity>
      <TerrainMapped>false</TerrainMapped>
      <ImageAccessor>
        <LevelZeroTileSizeDegrees>36.0</LevelZeroTileSizeDegrees>
        <NumberLevels>11</NumberLevels>
        <TextureSizePixels>512</TextureSizePixels>
        <ImageFileExtension>jpeg</ImageFileExtension>
        <WMSAccessor>
          <ServerGetMapUrl>http://nvogre.phyast.pitt.edu/cgi-bin/nvomapserv</ServerGetMapUrl>
          <ServiceName>WMS</ServiceName>
          <Version>1.1.1</Version>
          <ImageFormat>image/jpeg</ImageFormat>
          <WMSLayerName>sdsslevel0,sdsslevel1,sdsslevel2&amp;TRANSPARENT=true</WMSLayerName>
          <UseTransparency>true</UseTransparency>
          <CacheExpirationTime>
            <Days>0</Days>
            <Hours>12</Hours>
            <Mins>0</Mins>
            <Seconds>0</Seconds>
          </CacheExpirationTime>
          <ServerLogoFilePath>add-ons\sdss\sdss\gal-footprint.png</ServerLogoFilePath>
        </WMSAccessor>
      </ImageAccessor>
    <TransparentColor><Red>0</Red><Green>0</Green><Blue>0</Blue></TransparentColor>

			<ExtendedInformation>
				<ToolBarImage>add-ons\sdss\sdss\gal-footprint.png</ToolBarImage>
			</ExtendedInformation>
		</QuadTileSet>

		<QuadTileSet ShowAtStartup="false">
			<Name> FIRST Footprint</Name>
			<DistanceAboveSurface>0</DistanceAboveSurface>
			<BoundingBox>
				<North>
					<Value>90.</Value>
				</North>
				<South>
					<Value>-90.</Value>
				</South>
				<West>
					<Value>-180.</Value>
				</West>
				<East>
					<Value>180.</Value>
				</East>
			</BoundingBox>
			<Opacity>50</Opacity>
			<TerrainMapped>false</TerrainMapped>
			<ImageAccessor>
				<LevelZeroTileSizeDegrees>36.0</LevelZeroTileSizeDegrees>
				<NumberLevels>11</NumberLevels>
				<TextureSizePixels>512</TextureSizePixels>
				<ImageFileExtension>jpeg</ImageFileExtension>
		 	<WMSAccessor>
		 	  <ServerGetMapUrl>http://nvogre.phyast.pitt.edu/cgi-bin/nvomapserv</ServerGetMapUrl>
		 	  <ServiceName>WMS</ServiceName>
		 	  <Version>1.1.1</Version>
		 	  <ImageFormat>image/jpeg</ImageFormat>
	 		  <WMSLayerName>firstlevel0,firstlevel1</WMSLayerName>
	 		  <UseTransparency>true</UseTransparency>
			  <Opacity>50</Opacity>
	 		  <ServerLogoFilePath>add-ons\sdss\sdss\gal-footprint2.png</ServerLogoFilePath>
		 	 </WMSAccessor>
			</ImageAccessor>
			<ExtendedInformation>
				<ToolBarImage>add-ons\sdss\sdss\gal-footprint2.png</ToolBarImage>
			</ExtendedInformation>
		</QuadTileSet>

	</ChildLayerSet>
</LayerSet>
