=== MFW3D/MFW3DNet/bin/Release/Plugins/NRLMonterey/NRL_Monterey.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by Patrick Hogan (private) -->
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="NRL_DataSet_List">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="NRL_DataSet" type="NRL_DataSet" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="NRL_DataSet">
		<xs:choice>
			<xs:element name="ChildDataSets">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="NRL_DataSet" type="NRL_DataSet" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:sequence>
				<xs:element name="Directory_Url" type="xs:string"/>
				<xs:element name="Description" type="xs:string"/>
				<xs:element name="GeographicBoundingBox" type="GeographicBoundingBox"/>
				<xs:element name="Directory_Keyword_Filter" type="xs:string" minOccurs="0"/>
			</xs:sequence>
		</xs:choice>
		<xs:attribute name="Name" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="GeographicBoundingBox">
		<xs:sequence>
			<xs:element name="North" type="LatitudeCoordinate"/>
			<xs:element name="South" type="LatitudeCoordinate"/>
			<xs:element name="West" type="LongitudeCoordinate"/>
			<xs:element name="East" type="LongitudeCoordinate"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="LongitudeCoordinate">
		<xs:sequence>
			<xs:element name="Value">
				<xs:simpleType>
					<xs:restriction base="xs:double">
						<xs:minInclusive value="-180"/>
						<xs:maxInclusive value="180"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="LatitudeCoordinate">
		<xs:sequence>
			<xs:element name="Value">
				<xs:simpleType>
					<xs:restriction base="xs:double">
						<xs:minInclusive value="-90"/>
						<xs:maxInclusive value="90"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== MFW3D/MFW3DNet/bin/Release/Plugins/NRLMonterey/NRL_Monterey.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by Patrick Hogan (private) -->
<NRL_DataSet_List xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\WorldWind\bin\Debug\Configuration\NRL_Monterey.xsd">
	<NRL_DataSet Name="Global">
		<ChildDataSets>
			<NRL_DataSet Name="Cloud Top Heights">
				<Directory_Url>http://www.nrlmry.navy.mil/archdat/global/stitched/cloudtop/</Directory_Url>
				<Description>Global Cloud Top Heights</Description>
				<GeographicBoundingBox>
					<North><Value>75</Value></North>
					<South><Value>-75</Value></South>
					<West><Value>-180</Value></West>
					<East><Value>180</Value></East>
				</GeographicBoundingBox>
			</NRL_DataSet>
			<NRL_DataSet Name="Blue Marble day and night">
				<Directory_Url>http://www.nrlmry.navy.mil/archdat/global/stitched/day_night_bm/</Directory_Url>
				<Description>Blue Marble day and night</Description>
				<GeographicBoundingBox>
					<North><Value>64.87212</Value></North>
					<South><Value>-65.12525</Value></South>
					<West><Value>-180</Value></West>
					<East><Value>180</Value></East>
				</GeographicBoundingBox>
			</NRL_DataSet>
			<NRL_DataSet Name="IR">
				<Directory_Url>http://www.nrlmry.navy.mil/archdat/global/stitched/ir/</Directory_Url>
				<GeographicBoundingBox>
					<North><Value>65</Value></North>
					<South><Value>-65</Value></South>
					<West><Value>-180</Value></West>
					<East><Value>180</Value></East>
				</GeographicBoundingBox>
			</NRL_DataSet>
			<NRL_DataSet Name="IR Color">
				<Directory_Url>http://www.nrlmry.navy.mil/archdat/global/rain/ir_color/</Directory_Url>
				<GeographicBoundingBox>
					<North><Value>60</Value></North>
					<South><Value>-60</Value></South>
					<West><Value>-180</Value></West>
					<East><Value>180</Value></East>
				</GeographicBoundingBox>
			</NRL_DataSet>
			<NRL_DataSet Name="Vis Color">
				<Directory_Url>http://www.nrlmry.navy.mil/archdat/global/rain/vis_color/</Directory_Url>
				<GeographicBoundingBox>
					<North><Value>60</Value></North>
					<South><Value>-60</Value></South>
					<West><Value>-180</Value></West>
					<East><Value>180</Value></East>
				</GeographicBoundingBox>
			</NRL_DataSet>
			<NRL_DataSet Name="Water Vapor">
				<Directory_Url>http://www.nrlmry.navy.mil/archdat/global/stitched/vapor/</Directory_Url>
				<GeographicBoundingBox>
					<North><Value>65</Value></North>
					<South><Value>-65</Value></South>
					<West><Value>-180</Value></West>
					<East><Value>180</Value></East>
				</GeographicBoundingBox>
			</NRL_DataSet>
			<NRL_DataSet Name="Visible">
				<Directory_Url>http://www.nrlmry.navy.mil/archdat/global/stitched/vis/</Directory_Url>
				<GeographicBoundingBox>
					<North><Value>65</Value></North>
					<South><Value>-65</Value></South>
					<West><Value>-180</Value></West>
					<East><Value>180</Value></East>
				</GeographicBoundingBox>
			</NRL_DataSet>
			<NRL_DataSet Name="Land">
				<ChildDataSets>
					<NRL_DataSet Name="Soil Moisture">
						<Directory_Url>http://www.nrlmry.navy.mil/archdat/global/land/soil_moisture/</Directory_Url>
						<GeographicBoundingBox>
							<North><Value>90</Value></North>
							<South><Value>-90</Value></South>
							<West><Value>-180</Value></West>
							<East><Value>180</Value></East>
						</GeographicBoundingBox>
					</NRL_DataSet>
					<NRL_DataSet Name="Surface Type">
						<Directory_Url>http://www.nrlmry.navy.mil/archdat/global/land/surface_type/</Directory_Url>
						<GeographicBoundingBox>
							<North><Value>90</Value></North>
							<South><Value>-90</Value></South>
							<West><Value>-180</Value></West>
							<East><Value>180</Value></East>
						</GeographicBoundingBox>
					</NRL_DataSet>
					<NRL_DataSet Name="Vegetation Water Content">
						<Directory_Url>http://www.nrlmry.navy.mil/archdat/global/land/veg_water_content/</Directory_Url>
						<GeographicBoundingBox>
							<North><Value>90</Value></North>
							<South><Value>-90</Value></South>
							<West><Value>-180</Value></West>
							<East><Value>180</Value></East>
						</GeographicBoundingBox>
					</NRL_DataSet>
					<NRL_DataSet Name="AMSRE">
						<ChildDataSets>
							<NRL_DataSet Name="10v-10h">
								<Directory_Url>http://www.nrlmry.navy.mil/archdat/global/land/amsre/10v-10h/</Directory_Url>
								<GeographicBoundingBox>
									<North><Value>70</Value></North>
									<South><Value>-70</Value></South>
									<West><Value>-180</Value></West>
									<East><Value>180</Value></East>
								</GeographicBoundingBox>
							</NRL_DataSet>
							<NRL_DataSet Name="6v-6h">
								<Directory_Url>http://www.nrlmry.navy.mil/archdat/global/land/amsre/6v-6h/</Directory_Url>
								<GeographicBoundingBox>
									<North><Value>70</Value></North>
									<South><Value>-70</Value></South>
									<West><Value>-180</Value></West>
									<East><Value>180</Value></East>
								</GeographicBoundingBox>
							</NRL_DataSet>
							<NRL_DataSet Name="PGR">
								<Directory_Url>http://www.nrlmry.navy.mil/archdat/global/land/amsre/PGR/</Directory_Url>
								<GeographicBoundingBox>
									<North><Value>70</Value></North>
									<South><Value>-70</Value></South>
									<West><Value>-180</Value></West>
									<East><Value>180</Value></East>
								</GeographicBoundingBox>
							</NRL_DataSet>
							<NRL_DataSet Name="SGR">
								<Directory_Url>http://www.nrlmry.navy.mil/archdat/global/land/amsre/sgr/</Directory_Url>
								<GeographicBoundingBox>
									<North><Value>70</Value></North>
									<South><Value>-70</Value></South>
									<West><Value>-180</Value></West>
									<East><Value>180</Value></East>
								</GeographicBoundingBox>
							</NRL_DataSet>
						</ChildDataSets>
					</NRL_DataSet>
				</ChildDataSets>
			</NRL_DataSet>
			<NRL_DataSet Name="Rain Accumulations">
				<ChildDataSets>
					<NRL_DataSet Name="Geo">
						<ChildDataSets>
							<NRL_DataSet Name="2 Week">
								<Directory_Url>http://www.nrlmry.navy.mil/archdat/global/rain/accumulations/geo/2-week/</Directory_Url>
								<GeographicBoundingBox>
									<North><Value>60</Value></North>
									<South><Value>-60</Value></South>
									<West><Value>-180</Value></West>
									<East><Value>180</Value></East>
								</GeographicBoundingBox>
							</NRL_DataSet>
							<NRL_DataSet Name="12 Day">
								<Directory_Url>http://www.nrlmry.navy.mil/archdat/global/rain/accumulations/geo/12-day/</Directory_Url>
								<GeographicBoundingBox>
									<North><Value>60</Value></North>
									<South><Value>-60</Value></South>
									<West><Value>-180</Value></West>
									<East><Value>180</Value></East>
								</GeographicBoundingBox>
							</NRL_DataSet>
							<NRL_DataSet Name="10 Day">
								<Directory_Url>http://www.nrlmry.navy.mil/archdat/global/rain/accumulations/geo/10-day</Directory_Url>
								<GeographicBoundingBox>
									<North><Value>60</Value></North>
									<South><Value>-60</Value></South>
									<West><Value>-180</Value></West>
									<East><Value>180</Value></East>
								</GeographicBoundingBox>
							</NRL_DataSet>
							<NRL_DataSet Name="1 Week">
								<Directory_Url>http://www.nrlmry.navy.mil/archdat/global/rain/accumulations/geo/1-week</Directory_Url>
								<GeographicBoundingBox>
									<North><Value>60</Value></North>
									<South><Value>-60</Value></South>
									<West><Value>-180</Value></West>
									<East><Value>180</Value></East>
								</GeographicBoundingBox>
							</NRL_DataSet>
							<NRL_DataSet Name="6 Day">
								<Directory_Url>http://www.nrlmry.navy.mil/archdat/global/rain/accumulations/geo/6-day</Directory_Url>
								<GeographicBoundingBox>
									<North><Value>60</Value></North>
									<South><Value>-60</Value></South>
									<West><Value>-180</Value></West>
									<East><Value>180</Value></East>
								</GeographicBoundingBox>
							</NRL_DataSet>
							<NRL_DataSet Name="5 Day">
								<Directory_Url>http://www.nrlmry.navy.mil/archdat/global/rain/accumulations/geo/5-day</Directory_Url>
								<GeographicBoundingBox>
									<North><Value>60</Value></North>
									<South><Value>-60</Value></South>
									<West><Value>-180</Value></West>
									<East><Value>180</Value></East>
								</GeographicBoundingBox>
							</NRL_DataSet>
							<NRL_DataSet Name="4 Day">
								<Directory_Url>http://www.nrlmry.navy.mil/archdat/global/rain/accumulations/geo/4-day</Directory_Url>
								<GeographicBoundingBox>
									<North><Value>60</Value></North>
									<South><Value>-60</Value></South>
									<West><Value>-180</Value></West>
									<East><Value>180</Value></East>
								</GeographicBoundingBox>
							</NRL_DataSet>
							<NRL_DataSet Name="3 Day">
								<Directory_Url>http://www.nrlmry.navy.mil/archdat/global/rain/accumulations/geo/3-day</Directory_Url>
								<GeographicBoundingBox>
									<North><Value>60</Value></North>
									<South><Value>-60</Value></South>
									<West><Value>-180</Value></West>
									<East><Value>180</Value></East>
								</GeographicBoundingBox>
							</NRL_DataSet>
							<NRL_DataSet Name="2 Day">
								<Directory_Url>http://www.nrlmry.navy.mil/archdat/global/rain/accumulations/geo/2-day</Directory_Url>
								<GeographicBoundingBox>
									<North><Value>60</Value></North>
									<South><Value>-60</Value></South>
									<West><Value>-180</Value></West>
									<East><Value>180</Value></East>
								</GeographicBoundingBox>
							</NRL_DataSet>
							<NRL_DataSet Name="24 Hour">
								<Directory_Url>http://www.nrlmry.navy.mil/archdat/global/rain/accumulations/geo/24-hour</Directory_Url>
								<GeographicBoundingBox>
									<North><Value>60</Value></North>
									<South><Value>-60</Value></South>
									<West><Value>-180</Value></West>
									<East><Value>180</Value></East>
								</GeographicBoundingBox>
							</NRL_DataSet>
